
name: Userguide rebuild

#
# update the userguide every three months
#

on:
  schedule:
    - cron: '0 0 1 1,3,6,9,12 *'
  workflow_dispatch:

jobs:
  update-userguid:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - name: Install LateX dependencies
      run: sudo apt-get install -qq latex2html texlive-font-utils
    - name: Build userguide
      run: |
        rm -rf guide
        mkdir guide
        git clone git@github.com:MGX-metagenomics/userguide.git
        cd userguide
        make
        mv main/* ../guide/
    - name: Commit latex2html guide
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "latex2html userguide rebuild [ci skip]"
        file_pattern: 'guide/*'

